# -*- coding: utf-8 -*-
from odoo import http
from odoo.http import request


class BraintreeController(http.Controller):
    """ Braintree Payment Controller """

    @http.route('/payment/braintree/process', type='json', auth='public', csrf=False)
    def braintree_process(self, reference, nonce, **kwargs):
        """
        Receive the payment nonce from the frontend and process the transaction.

        :param str reference: The unique reference of the payment transaction.
        :param str nonce: The secure payment method nonce generated by Braintree.
        :param dict kwargs: Additional keyword arguments.
        :return: A dictionary containing the success status and an optional error message.
        :rtype: dict
        """
        tx = request.env['payment.transaction'].sudo().search([
            ('reference', '=', reference)
        ], limit=1)

        if not tx:
            return {
                'success': False,
                'message': 'Transaction not found',
            }

        try:
            tx._send_braintree_payment(nonce)
            return {'success': True}
        except Exception as e:
            return {
                'success': False,
                'message': str(e),
            }