# -*- coding: utf-8 -*-
from . import subscription_plan
from . import subscription_price_lock
from . import res_partner
from . import stock_picking
from . import subscription_close_reason
from . import product_template
from . import sale_order
from . import account_move
from . import sale_order_template
from . import subscription_reports
from . import subscription_dashboard
from . import subscription_whatsapp_template
from . import subscription_usage
from . import loyalty_program
from . import subscription_proration
from . import subscription_dunning
from . import res_config_settings
from . import payment_transaction
from . import product_pricelist
