# -*- coding: utf-8 -*-
from odoo import models
from odoo.exceptions import ValidationError


class PaymentTransaction(models.Model):
    """ Braintree Payment Transaction """
    _inherit = 'payment.transaction'

    def _send_braintree_payment(self, nonce):
        """
        Send the payment nonce to Braintree to process the final transaction.

        :param str nonce: The secure payment method nonce generated by Braintree.
        :return: The Braintree transaction object if successful.
        :rtype: braintree.Transaction
        :raises ValidationError: If the payment is declined or fails.
        """
        self.ensure_one()
        gateway = self.provider_id._get_braintree_gateway()
        result = gateway.transaction.sale({
            'amount': str(self.amount),
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })
        if result.is_success:
            self.provider_reference = result.transaction.id
            self._set_done()
            return result.transaction
        error_message = 'Payment Failed'
        if result.errors:
            errors = []
            for error in result.errors.deep_errors:
                errors.append(error.message)
            error_message = '\n'.join(errors)
        elif result.transaction and result.transaction.processor_response_text:
            error_message = result.transaction.processor_response_text
        self._set_error(error_message)
        raise ValidationError(error_message)